---
title: "Index"
output: html_document
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

There are two kinds of simulations in this directory.

1) [In the ReproSim directory, we simulate according to the patterns of sharing present in the GTEX V6 Data, where 100 snps in cis of 500 genes with $\hat{\beta}$ and standard errors available across 44 tissues, and there is sharing according to gtex covariance matrices 2:9 (See Urbut et al). In this directory, we walk the user through a step by step analysis to reproduce the simulated results with a seed, and provide ROC curves, RMSE computations and patterns of sharing, etc.](Reprosim/newsim.html)

2) [I add the ability to run with SFA, explaining to users how this is done](SFA/running_with_sfa.html)

2) [In the `Advanced Directory', we also demonstrate how the software could be used when correlated errors are suspected, and the matrix of correlation among the errors is known.](Advanced/testingvmat.html)

2) [In the `Advanced Directory', the purpose of the tissue-specificity simulations are to simulate according to both the patterns of sharing mentioned above and according to tissue specificity; accordingly, 35% are simulated according to a randomly chosen tissue specific configuration.
Thus there are 50,000 gene snp pairs, and 400 'true'. We also want to compare to the results using univariate methods (ASH) and I also show at how well our method captures a 'tissue specific association.](Advanced/TissueSpecificVignette.html)

